# Site settings
title: Truong Duc Duy's Blog
description: >
  Blog về Lập trình Android, phát triển Web và tất tần tật những thứ mà mình muốn chia sẻ.
  Android development, Web development and all the things I want to share.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://duytruong.github.io" # the base hostname & protocol for your site

author:
  fullname: Trương Đức Duy
  googleplus:
  github: duytruong
  twitter:
  disqus: duytruong
  facebook: truongduy93

google_analytics: UA-63845323-1

# Build settings
markdown: kramdown
gems:
  - jemoji
